
export const GET_RECIPES = 'GET_RECIPES'
export const GET_ERRORS = 'GET_ERRORS'

export const DELETE_RECIPES = 'DELETE_RECIPES'
export const UPDATE_RECIPE = 'UPDATE_RECIPE'

export const ADD_RECIPE = 'ADD_RECIPE'
export const GET_RECIPE = 'GET_RECIPE'
export const DELETE_RECIPE = 'DELETE_RECIPE'

export const POST_STEP = 'POST_STEP'
export const DELETE_STEP = 'DELETE_STEP'
export const SELECTED_RECIPE = 'SELECTED_RECIPE'
export const RECIPE_LOADING = 'RECIPE_LOADING'